### ISSUE TITLE
getBoundingClientRect of null

### ISSUE THREAD

**Issue by ai** [animakit/animakit-elastic#6]
We added Sentry to Amplifr and found that issue:

```
TypeError: Cannot read property 'getBoundingClientRect' of null
  at calcDimensions(./node_modules/animakit-elastic/lib/AnimakitElastic.js:233:1)
  at repaint(./node_modules/animakit-elastic/lib/AnimakitElastic.js:263:1)
  at apply(./node_modules/animakit-elastic/lib/AnimakitElastic.js:161:1)
  at wrapped(raven.js:442:21)
```

Seems like we need some `if (this.contentNode)` there.

@askd what doy ou think?

**Comment by askd** [comment]
Thank you for the issue!
Fixed here: https://github.com/animakit/animakit-elastic/commit/d7ff007fc88225dab38e015131c783814ee10df7
I've just released new 1.1.4 version.
